services:
  - type: web
    name: civik-link
    env: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker server.app:app
    plan: free
    region: singapore # Choose closest to user
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        value: ./civik.db
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM
        sync: false
